# Generated by infrastructure/release/publish-operator.sh. Do not edit by hand.
class Nebulai < Formula
  desc "Install and operate a self-hosted Nebulai deployment"
  homepage "https://nebulai.uk"
  version "0.3.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.3.0/nebulai-darwin-arm64"
      sha256 "c35d16e5a871e6f98cbcbf42f4f95887320171d2c99759c4479ee7c950ce8817"
    end
    on_intel do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.3.0/nebulai-darwin-amd64"
      sha256 "4f38748b1a78b1f9cd672a31356b70600df3a84b592cf8b4115fae6a4ee54217"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.3.0/nebulai-linux-arm64"
      sha256 "cc32522d0f0b7f2d1c238e707468f69fb03d2600dbf26a77030ea04afa10e1aa"
    end
    on_intel do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.3.0/nebulai-linux-amd64"
      sha256 "5ed329f0dafd3792f2622102e5a2e00146f6caeac9138e6543466c1c8bb0ecc8"
    end
  end

  def install
    bin.install Dir["nebulai-*"].reject { |name| name.end_with?(".sha256") }.first => "nebulai"
  end

  test do
    assert_match "nebulai", shell_output("#{bin}/nebulai --help")
  end
end
