# Generated by infrastructure/release/publish-operator.sh. Do not edit by hand.
class Nebulai < Formula
  desc "Install and operate a self-hosted Nebulai deployment"
  homepage "https://nebulai.uk"
  version "0.2.2"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.2.2/nebulai-darwin-arm64"
      sha256 "18dbc6bd53f58fd6b7dac54a1b0a4d316d0e9b956b2c44451f9e6a8fbe2d3d3d"
    end
    on_intel do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.2.2/nebulai-darwin-amd64"
      sha256 "a728fc4f6ff4dca3a13b99e22190f3b07916bf26afc8573e884f4071c916dad1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.2.2/nebulai-linux-arm64"
      sha256 "2a1f51bd2ed18e99f2cffe6941041acbca24fd97b9888a16f07f3abde37cbd56"
    end
    on_intel do
      url "https://github.com/KaiserVermillion/nebulai-releases/releases/download/operator-v0.2.2/nebulai-linux-amd64"
      sha256 "83806d23f3142a5b674ee91cf13dbd910820d4d0732ac9e1b2771e77a28a5f86"
    end
  end

  def install
    bin.install Dir["nebulai-*"].reject { |name| name.end_with?(".sha256") }.first => "nebulai"
  end

  test do
    assert_match "nebulai", shell_output("#{bin}/nebulai --help")
  end
end
